INSERT INTO TYPEPRODUCT (TYPE_PRODUCT_NAME)
VALUES ('vaso');
INSERT INTO TYPEPRODUCT (TYPE_PRODUCT_NAME)
VALUES ('camiseta');
INSERT INTO TYPEPRODUCT (TYPE_PRODUCT_NAME)
VALUES ('comic');
INSERT INTO TYPEPRODUCT (TYPE_PRODUCT_NAME)
VALUES ('juguete');
INSERT INTO TYPEPRODUCT (TYPE_PRODUCT_NAME)
VALUES ('accesorio');

INSERT INTO BRAND (BRAND_NAME)
VALUES ('Marvel');
INSERT INTO BRAND (BRAND_NAME)
VALUES ('DC comics');
INSERT INTO BRAND (BRAND_NAME)
VALUES ('Alternativo de la comunidad');

INSERT INTO INVENTORY (INVENTORY_NAME)
VALUES ('Inventario 2018');

INSERT INTO PRODUCT (PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, BRAND_ID, INVENTORY_ID, PRODUCT_TYPE_ID )
VALUES ('Vaso capitan america', 50, 5, 1, 1, 1);
INSERT INTO PRODUCT (PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, BRAND_ID, INVENTORY_ID, PRODUCT_TYPE_ID )
VALUES ('Vaso capitan america', 36, 7, 2, 1, 1);
INSERT INTO PRODUCT (PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, BRAND_ID, INVENTORY_ID, PRODUCT_TYPE_ID )
VALUES ('Vaso capitan america', 2, 2, 3, 1, 1);
INSERT INTO PRODUCT (PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, BRAND_ID, INVENTORY_ID, PRODUCT_TYPE_ID )
VALUES ('Vaso hulk', 2, 0, 1, 1, 1);
INSERT INTO PRODUCT (PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, BRAND_ID, INVENTORY_ID, PRODUCT_TYPE_ID )
VALUES ('revista', 23, 2, 1, 1, 3);
INSERT INTO PRODUCT (PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, BRAND_ID, INVENTORY_ID, PRODUCT_TYPE_ID )
VALUES ('lapicero', 10, 2, 1, 1, 5);